package wiley.training.advanced.miniproject1;
/*
Banking Application:

1)Create account
2)Authorisation(using passwords)
3)Credit/Debit
4)Check balance
5)Get statement(all transactions)

Class structure:
-member variables:
	**All member variables are private
	-name
	-unique id(autogenerated)
	-email
	-password(static hash table)
	-balance
	-logs(for transactions)
-member functions:
	**Getter/Setter methods for all member variables
	-createAccount
	-checkBalance
	-deposit
	-withdraw
	-displayLogs(display all the previous transactions)
	-changePassword
	-deleteAccount
*/